### ISSUE TITLE
`check` doesn't return `Bool` when counterexamples found

### ISSUE THREAD

**Issue by kapple19** [Seelengrab/PropCheck.jl#15]
Loving the package so far!

In the documented examples, expressions of the form
```julia
@test check(...)
```
are provided.

Since `check` only returns `true` or the value of the counter example, I don't think this is appropriate usage. I've had to write my own wrapper for my use cases. The one I found that works for me is
```julia
function wrap_check(prop::Function, gen::Integrated)
    chk = check(prop, gen)
    chk isa Bool && return chk
    @test prop(chk)
    return false
end
```
and then called it as
```julia
@test wrap_check(prop, gen)
```

I'm not too familiar with `PropCheck.jl` internals. I think the type instability of `check`'s return values are somewhat justified for what it's trying to achieve. But I thought I might bring this up because people wanting to use your package would go down your package documentation's idiomatic usage and then travel down the road of discovery I went on.

On the other hand, we choose to be fine with `PropCheck.jl` reporting counterexample finds as `Expression evaluated to non-Boolean` test errors instead of test failures, the former of which I'm not a fan of.

**Comment by Seelengrab** [comment]
> Loving the package so far!


Thank you! Nice to hear that someone is using this :)

> Since check only returns true or the value of the counter example, I don't think this is appropriate usage.

This is intentional - it was the easiest way of getting the found counterexample reported as part of a testsuite, making use of `@testset`. As is, `check` should only ever return a `Bool` if the result is `true`, and a non-`Bool` counterexample otherwise. This is subtly broken if the counterexample itself is `true`:

```julia
julia> using PropCheck

julia> prop(b) = !b
prop (generic function with 1 method)

julia> using Test

julia> PropCheck.check(prop, PropCheck.itype(Bool))
┌ Info: Found counterexample for 'prop', beginning shrinking...
└   Counterexample = true
[ Info: 1 counterexamples found for prop
true

julia> @test PropCheck.check(prop, PropCheck.itype(Bool))
┌ Info: Found counterexample for 'prop', beginning shrinking...
└   Counterexample = true
[ Info: 1 counterexamples found for prop
Test Passed
```

which is of course a bit bad. I intended to eventually replace this `@test check` approach entirely with a solution based on a custom `AbstractTestSet`, which would avoid that problem, but never got to it. Part of the reason is that support for printing of custom testsets was only recently merged into Julia, see https://github.com/JuliaLang/julia/pull/53215. Another reason is that I'm currently working on a package that already handles this & much more better, while being faster :)

As for changing what `check` itself returns - that likely won't change at all, if I'm going to change the user-facing API it'd be by replacing `@ŧest` with a different macro entirely.

**Comment by kapple19** [comment]
You... you've got another packing coming that does `PropCheck.jl` stuff but better? Well then, I'm excited for that!

As for what `check` itself returns, I'm fine with its user-facing API to stay as it is for now. As for my wrapper, here's an improved update for anyone looking for a workaround. I understand why it was designed that way, I just felt the need to point out the discord between your documentation of usage examples and idiomatic Julia testing.

```julia
function wrap_check(prop::Function, gen::Integrated)
    chk = check(splat(prop), gen)
    chk isa Bool && return chk
    @info chk
    return prop(chk[1]...)
end
```

It grabs the counterexample and feeds it back to the property-checking function. So I can have `@test wrap_check(...)` throughout my test code, and upon finding counterexamples it'll have run the counterexample on `prop` and returned the false value with a nicer report than a test error.

Keep up the great work @Seelengrab
